"""add_granular_fields_to_documents

Revision ID: 5909995c26da
Revises: a373475f4c69
Create Date: 2026-05-24 00:16:04.985091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5909995c26da'
down_revision: Union[str, Sequence[str], None] = 'a373475f4c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pays', sa.String(length=50), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('matiere', sa.String(length=50), nullable=False),
    sa.Column('chapitre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('methode_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formules_cles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pieges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frequence_exam', sa.String(length=30), nullable=False),
    sa.Column('difficulte', sa.Integer(), nullable=False),
    sa.Column('exemple_resolu', sa.Text(), nullable=True),
    sa.Column('exercice_type', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_exercise_types_chapitre'), 'exercise_types', ['chapitre'], unique=False)
    op.create_index(op.f('ix_exercise_types_exam_type'), 'exercise_types', ['exam_type'], unique=False)
    op.create_index(op.f('ix_exercise_types_matiere'), 'exercise_types', ['matiere'], unique=False)
    op.create_index(op.f('ix_exercise_types_pays'), 'exercise_types', ['pays'], unique=False)
    op.create_index(op.f('ix_exercise_types_serie'), 'exercise_types', ['serie'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matiere', sa.String(length=50), nullable=False),
    sa.Column('chapitre', sa.String(length=100), nullable=True),
    sa.Column('exercise_type_slug', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('reponse', sa.Text(), nullable=False),
    sa.Column('methode_utilisee', sa.String(length=100), nullable=True),
    sa.Column('question_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_chapitre'), 'knowledge_base', ['chapitre'], unique=False)
    op.create_index(op.f('ix_knowledge_base_exercise_type_slug'), 'knowledge_base', ['exercise_type_slug'], unique=False)
    op.create_index(op.f('ix_knowledge_base_matiere'), 'knowledge_base', ['matiere'], unique=False)
    op.create_table('student_chapter_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('matiere', sa.String(length=50), nullable=False),
    sa.Column('chapitre', sa.String(length=100), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=False),
    sa.Column('types_vus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('types_maitrises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('types_faibles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weak_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_style', sa.String(length=30), nullable=False),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_chapter_mastery_chapitre'), 'student_chapter_mastery', ['chapitre'], unique=False)
    op.create_index(op.f('ix_student_chapter_mastery_matiere'), 'student_chapter_mastery', ['matiere'], unique=False)
    op.create_index(op.f('ix_student_chapter_mastery_user_id'), 'student_chapter_mastery', ['user_id'], unique=False)
    op.add_column('document_chunks', sa.Column('pays', sa.String(length=50), nullable=True))
    op.add_column('document_chunks', sa.Column('serie', sa.String(length=20), nullable=True))
    op.add_column('document_chunks', sa.Column('matiere', sa.String(length=50), nullable=True))
    op.add_column('document_chunks', sa.Column('chapitre', sa.String(length=100), nullable=True))
    op.add_column('document_chunks', sa.Column('doc_type', sa.String(length=30), nullable=True))
    op.add_column('document_chunks', sa.Column('annee', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('niveau', sa.Integer(), nullable=True, server_default='2'))
    op.add_column('document_chunks', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_document_chunks_series'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_subject'), table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_chapitre'), 'document_chunks', ['chapitre'], unique=False)
    op.create_index(op.f('ix_document_chunks_doc_type'), 'document_chunks', ['doc_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_matiere'), 'document_chunks', ['matiere'], unique=False)
    op.create_index(op.f('ix_document_chunks_pays'), 'document_chunks', ['pays'], unique=False)
    op.create_index(op.f('ix_document_chunks_serie'), 'document_chunks', ['serie'], unique=False)
    op.drop_column('document_chunks', 'series')
    op.drop_column('document_chunks', 'subject')
    op.add_column('documents', sa.Column('pays', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('serie', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('matiere', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('chapitre', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('sous_chapitre', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('annee', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('niveau', sa.Integer(), nullable=True, server_default='2'))
    op.add_column('documents', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('langue', sa.String(length=10), nullable=True, server_default='fr'))
    op.create_index(op.f('ix_documents_chapitre'), 'documents', ['chapitre'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_exam_type'), 'documents', ['exam_type'], unique=False)
    op.create_index(op.f('ix_documents_matiere'), 'documents', ['matiere'], unique=False)
    op.create_index(op.f('ix_documents_pays'), 'documents', ['pays'], unique=False)
    op.create_index(op.f('ix_documents_serie'), 'documents', ['serie'], unique=False)
    op.drop_column('documents', 'series')
    op.drop_column('documents', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('series', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_serie'), table_name='documents')
    op.drop_index(op.f('ix_documents_pays'), table_name='documents')
    op.drop_index(op.f('ix_documents_matiere'), table_name='documents')
    op.drop_index(op.f('ix_documents_exam_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_chapitre'), table_name='documents')
    op.drop_column('documents', 'langue')
    op.drop_column('documents', 'source')
    op.drop_column('documents', 'niveau')
    op.drop_column('documents', 'annee')
    op.drop_column('documents', 'sous_chapitre')
    op.drop_column('documents', 'chapitre')
    op.drop_column('documents', 'matiere')
    op.drop_column('documents', 'serie')
    op.drop_column('documents', 'pays')
    op.add_column('document_chunks', sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('series', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_chunks_serie'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_pays'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_matiere'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_doc_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chapitre'), table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_subject'), 'document_chunks', ['subject'], unique=False)
    op.create_index(op.f('ix_document_chunks_series'), 'document_chunks', ['series'], unique=False)
    op.drop_column('document_chunks', 'keywords')
    op.drop_column('document_chunks', 'niveau')
    op.drop_column('document_chunks', 'annee')
    op.drop_column('document_chunks', 'doc_type')
    op.drop_column('document_chunks', 'chapitre')
    op.drop_column('document_chunks', 'matiere')
    op.drop_column('document_chunks', 'serie')
    op.drop_column('document_chunks', 'pays')
    op.drop_index(op.f('ix_student_chapter_mastery_user_id'), table_name='student_chapter_mastery')
    op.drop_index(op.f('ix_student_chapter_mastery_matiere'), table_name='student_chapter_mastery')
    op.drop_index(op.f('ix_student_chapter_mastery_chapitre'), table_name='student_chapter_mastery')
    op.drop_table('student_chapter_mastery')
    op.drop_index(op.f('ix_knowledge_base_matiere'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_exercise_type_slug'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_chapitre'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_exercise_types_serie'), table_name='exercise_types')
    op.drop_index(op.f('ix_exercise_types_pays'), table_name='exercise_types')
    op.drop_index(op.f('ix_exercise_types_matiere'), table_name='exercise_types')
    op.drop_index(op.f('ix_exercise_types_exam_type'), table_name='exercise_types')
    op.drop_index(op.f('ix_exercise_types_chapitre'), table_name='exercise_types')
    op.drop_table('exercise_types')
    # ### end Alembic commands ###
