"""create_users_and_config_tables

Revision ID: 6584ae1a20b6
Revises: 
Create Date: 2026-05-22 19:55:30.515579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6584ae1a20b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_config_key'), 'platform_config', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('onboarding_step', sa.String(length=30), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('series', sa.String(length=20), nullable=True),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_messages_used', sa.Integer(), nullable=False),
    sa.Column('daily_messages_bonus', sa.Integer(), nullable=False),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by_id', sa.UUID(), nullable=True),
    sa.Column('last_upsell_shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upsell_refused_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platform_config_key'), table_name='platform_config')
    op.drop_table('platform_config')
    # ### end Alembic commands ###
