"""create_messages_table

Revision ID: acaf1250bd1b
Revises: b3d2280ca026
Create Date: 2026-05-22 21:19:43.672524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaf1250bd1b'
down_revision: Union[str, Sequence[str], None] = 'b3d2280ca026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('msg_type', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_whatsapp_id'), 'messages', ['whatsapp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_whatsapp_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
