"""add_streak_last_active_and_subjects_to_users

Revision ID: b3d2280ca026
Revises: 6eca3cfc0e71
Create Date: 2026-05-22 20:32:31.796555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3d2280ca026'
down_revision: Union[str, Sequence[str], None] = '6eca3cfc0e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('streak_last_active', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streak_last_active')
    op.drop_column('users', 'subjects')
    # ### end Alembic commands ###
